MIN_MATCH = 4

STRING = 0x0
BYTE_ARR = 0x01
NUMERIC_INT = 0x02
NUMERIC_FLOAT = 0x03
NUMERIC_LONG = 0x04
NUMERIC_DOUBLE = 0x05

SECOND = 1000
HOUR = 60 * 60 * SECOND
DAY = 24 * HOUR
SECOND_ENCODING = 0x40
HOUR_ENCODING = 0x80
DAY_ENCODING = 0xC0
BLOCK_SIZE = 128

INDEX_OPTION_NONE = 0
INDEX_OPTION_DOCS = 1
INDEX_OPTION_DOCS_FREQS = 2
INDEX_OPTION_DOCS_FREQS_POSITIONS = 3
INDEX_OPTION_DOCS_FREQS_POSITIONS_OFFSETS = 4

DOC_VALUES_NUMERIC = 0
DOC_VALUES_BINARY = 1
DOC_VALUES_SORTED = 2
DOC_VALUES_SORTED_SET = 3
DOC_VALUES_SORTED_NUMERIC = 4

DOC_DELTA_COMPRESSED = 0
DOC_GCD_COMPRESSED = 1
DOC_TABLE_COMPRESSED = 2
DOC_MONOTONIC_COMPRESSED = 3
DOC_CONST_COMPRESSED = 4
DOC_SPARSE_COMPRESSED = 5

DOC_BINARY_FIXED_UNCOMPRESSED = 0
DOC_BINARY_VARIABLE_UNCOMPRESSED = 1
DOC_BINARY_PREFIX_COMPRESSED = 2

DOC_SORTED_WITH_ADDRESSES = 0
DOC_SORTED_SINGLE_VALUED = 1
DOC_SORTED_SET_TABLE = 2

STORE_TERMVECTOR = 0x1
OMIT_NORMS = 0x2
STORE_PAYLOADS = 0x4

ALL_VALUES_EQUAL = 0

PACKED = 0
PACKED_SINGLE_BLOCK = 1